# Generated by Django 5.0.1 on 2024-01-22 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talklist',
            new_name='Tasklist',
        ),
    ]
